version: "3.9"
services:          
    contacts-service:
        build: ./contacts
    banking-service:
        build: ./BankingServiceCRUD
        ports:
            - 80:80
        depends_on:
            - contacts-service