version: "3.9"
services:          
    contacts-service:
        build: ./contacts
        ports:
            - 5001:5000 
    banking-service:
        build: ./BankingServiceCRUD
        ports:
            - 80:80
        depends_on:
            - contacts-service